name: Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Run Tests
      run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

    - name: Run Linting
      run: docker-compose run --rm app sh -c "flake8"
